"""Pure deterministic rendering using fixed, bundled standalone helper sources."""

import ast
import keyword
import math
from importlib.resources import files

from mlstudio.codegen.schemas import EffectiveExecutionPlan

# Fixed package resources are loaded once, not discovered from a Dataset or workspace.
# Their exact bytes are covered by source goldens and the generator version contract.
CSV_HELPERS = files("mlstudio.codegen").joinpath("csv_runtime.py").read_text(encoding="utf-8")
WORKLOAD_HELPERS = (
    files("mlstudio.codegen").joinpath("workload_runtime.py").read_text(encoding="utf-8")
)


def template_parts(source):
    """Separate fixed package imports from helpers; never inspect user-supplied code."""
    tree = ast.parse(source)
    imports, functions = [], []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(ast.get_source_segment(source, node))
        elif isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            functions.append(ast.get_source_segment(source, node))
    return imports, functions


CSV_IMPORTS, CSV_FUNCTIONS = template_parts(CSV_HELPERS)
RUNTIME_IMPORTS, RUNTIME_FUNCTIONS = template_parts(WORKLOAD_HELPERS)

IMPORTS = {
    "SimpleImputer": "sklearn.impute",
    "StandardScaler": "sklearn.preprocessing",
    "MinMaxScaler": "sklearn.preprocessing",
    "RobustScaler": "sklearn.preprocessing",
    "OneHotEncoder": "sklearn.preprocessing",
    "LogisticRegression": "sklearn.linear_model",
    "DecisionTreeClassifier": "sklearn.tree",
    "RandomForestClassifier": "sklearn.ensemble",
}


def literal(value):
    """Only builtin data, never object repr, identifiers, or executable fragments."""
    if value is None or type(value) in (str, bool, int):
        return ascii(value)
    if type(value) is float and math.isfinite(value):
        return repr(value)
    if type(value) in (list, tuple):
        left, right = ("[", "]") if type(value) is list else ("(", ")")
        return (
            left
            + ", ".join(literal(v) for v in value)
            + ("," if type(value) is tuple and len(value) == 1 else "")
            + right
        )
    if type(value) is dict and all(type(k) is str for k in value):
        return "{" + ", ".join(literal(k) + ": " + literal(value[k]) for k in sorted(value)) + "}"
    raise ValueError("Unsupported Python literal.")


def scalar_value(scalar):
    if scalar.value_type == "integer":
        return int(scalar.value)
    return scalar.value


def constructor(spec, indent=8):
    if spec.name not in IMPORTS:
        raise ValueError("Unsupported constructor.")
    parameters = []
    for key in sorted(spec.parameters):
        if not key.isidentifier() or key.startswith("_") or keyword.iskeyword(key):
            raise ValueError("Invalid constructor parameter.")
        value = spec.parameters[key]
        rendered = "np.nan" if key == "missing_values" and value == "nan" else literal(value)
        parameters.append(" " * (indent + 4) + key + "=" + rendered + ",")
    return spec.name + "(\n" + "\n".join(parameters) + "\n" + " " * indent + ")"


def generate(plan: EffectiveExecutionPlan) -> str:
    # Revalidate serialized input; no database, source loading, or default resolution here.
    plan = EffectiveExecutionPlan.model_validate(plan.model_dump())
    names = sorted({plan.model.name} | {op.name for f in plan.features for op in f.operations})
    imports = sorted(
        set(
            CSV_IMPORTS
            + RUNTIME_IMPORTS
            + [f"from {IMPORTS[name]} import {name}" for name in names]
        )
    )
    physical = {plan.target.column: plan.target.physical_dtype}
    physical.update({f.name: f.physical_dtype for f in plan.features})
    lines = [
        f"# Generated by {plan.generator}. Read-only current experiment source.",
        "# Runtime paths locate artifacts; Dataset identity is the ID and SHA-256 below.",
        "import argparse",
        "import sys",
        "from sklearn.compose import ColumnTransformer",
        "from sklearn.model_selection import train_test_split",
        "from sklearn.pipeline import Pipeline",
        *imports,
        "",
        "\n\n\n".join(CSV_FUNCTIONS),
        "",
        "\n\n\n".join(RUNTIME_FUNCTIONS),
        "",
        f"DATASET_ID = {literal(plan.dataset.dataset_id)}",
        f"DATASET_FINGERPRINT = {literal(plan.dataset.fingerprint)}",
        f"SOURCE_SIZE = {literal(plan.source.size_bytes)}",
        f"LIBRARIES = {literal(plan.implementation.libraries)}",
        f"PYTHON_VERSION = {literal(plan.implementation.python)}",
        f"TARGET = {literal(plan.target.column)}",
        f"POSITIVE_CLASS = {literal(scalar_value(plan.target.positive_class))}",
        f"NEGATIVE_CLASS = {literal(scalar_value(plan.target.negative_class))}",
        f"FEATURES = {literal([f.name for f in plan.features])}",
        f"PHYSICAL_DTYPES = {literal(physical)}",
        "",
        "",
        "def main():",
        "    parser = argparse.ArgumentParser(description='ML Studio classification workload')",
        "    parser.add_argument('--dataset', required=True)",
        "    parser.add_argument('--result', required=True)",
        "    parser.add_argument('--model', required=True)",
        "    args = parser.parse_args()",
        "    stage = 'runtime_inputs'",
        "    result_path = None",
        "    try:",
        "        dataset_path, result_path, model_path = runtime_paths(",
        "            args.dataset, args.result, args.model)",
        "        verify_environment(LIBRARIES, PYTHON_VERSION)",
        "        stage = 'data_loading'",
        "        source_bytes = read_verified_bytes(",
        "            dataset_path, DATASET_FINGERPRINT, SOURCE_SIZE)",
        "        frame = parse_csv_bytes(source_bytes)",
        "        if any(name not in frame or str(frame[name].dtype) != dtype",
        "               for name, dtype in PHYSICAL_DTYPES.items()):",
        "            raise ValueError('Source interpretation differs from the resolved plan.')",
        "        stage = 'target'",
        "        eligible = frame.loc[frame[TARGET].notna()]",
        "        y = eligible[TARGET]",
        "        if lossy_nullable_integers(y):",
        "            raise WorkloadValidationError(",
        "                'Unsupported nullable integer target precision.')",
        "        validate_target(y, scalar_record(POSITIVE_CLASS), scalar_record(NEGATIVE_CLASS))",
        "        X = eligible[FEATURES]",
        "",
        "        # Split before fitting any imputation, scaling, or category vocabulary.",
        "        stage = 'split'",
        "        X_train, X_test, y_train, y_test = train_test_split(",
        "            X, y,",
        f"            test_size={literal(plan.split.test_size)},",
        f"            random_state={literal(plan.split.random_seed)},",
        f"            stratify={'y' if plan.split.stratify else 'None'},",
        "            shuffle=True,",
        "        )",
        "        stage = 'training_partition_validation'",
        "        validate_training_partition(X_train, y_train)",
        "",
        "        # One branch per included feature, in immutable source-column order.",
        "        stage = 'preprocessing'",
        "        preprocessor = ColumnTransformer(",
        "            transformers=[",
    ]
    for index, feature in enumerate(plan.features):
        branch = f"feature_{index:03d}"
        if feature.operations:
            lines.append(f"                ({literal(branch)}, Pipeline(steps=[")
            for number, op in enumerate(feature.operations):
                lines.append(f"                    ('step_{number}', {constructor(op, 24)}),")
            lines.append(f"                ]), {literal([feature.name])}),")
        else:
            lines.append(
                f"                ({literal(branch)}, 'passthrough', {literal([feature.name])}),"
            )
    lines.extend(
        [
            "            ],",
            f"            remainder={literal(plan.implementation.remainder)},",
            f"            sparse_threshold={literal(plan.implementation.sparse_threshold)},",
            "            n_jobs=1, verbose=False, verbose_feature_names_out=True,",
            "        )",
            f"        classifier = {constructor(plan.model)}",
            "        model_pipeline = Pipeline(steps=[",
            "            ('preprocessor', preprocessor), ('model', classifier)])",
            "",
            "        # This is the complete pipeline later persisted for raw-feature inference.",
            "        stage = 'training'",
            "        model_pipeline.fit(X_train, y_train)",
            "        stage = 'evaluation'",
            "        predictions = model_pipeline.predict(X_test)",
            "        metrics, matrix, auc_reason = evaluate_predictions(",
            "            model_pipeline, X_test, y_test, predictions,",
            "            POSITIVE_CLASS, NEGATIVE_CLASS",
            "        )",
            "        result = {",
            f"            'schema_version': {literal(plan.runtime.result_schema)},",
            "            'status': 'success',",
            "            'dataset': {'dataset_id': DATASET_ID,",
            "                        'fingerprint': DATASET_FINGERPRINT},",
            f"            'generator': {literal(plan.generator)},",
            "            'metrics': metrics, 'roc_auc_unavailable_reason': auc_reason,",
            "            'confusion_matrix': {",
            "                'labels': [scalar_record(NEGATIVE_CLASS),",
            "                           scalar_record(POSITIVE_CLASS)],",
            "                'values': matrix,",
            "            },",
            "            'population': {'source': len(frame), 'eligible': len(y),",
            "                           'training': len(y_train), 'test': len(y_test)},",
            "            'artifacts': {'model': {'kind': 'complete_pipeline',",
            "                                    'filename': model_path.name}},",
            "            'versions': {'python': PYTHON_VERSION, **LIBRARIES},",
            "        }",
            "        json.dumps(result, allow_nan=False)",
            "        stage = 'artifact_output'",
            "        write_model(model_path, model_pipeline)",
            "        write_result(result_path, result)",
            "        return 0",
            "    except Exception as error:",
            "        # Never print exception text: library messages may contain raw rows or paths.",
            "        failure = {'schema_version': 'mlstudio-result-v1', 'status': 'failed',",
            "                   'stage': stage,",
            "                   'message': str(error)",
            "                   if isinstance(error, WorkloadValidationError)",
            "                   else 'Workload failed; review stage and configuration.'}",
            "        if result_path is not None:",
            "            try:",
            "                write_result(result_path, failure)",
            "            except Exception:",
            "                pass  # Nonzero exit still signals failure when storage also fails.",
            "        print('Workload failed during ' + stage + '.', file=sys.stderr)",
            "        return 1",
            "",
            "",
            "if __name__ == '__main__':",
            "    raise SystemExit(main())",
            "",
        ]
    )
    return "\n".join(lines).replace("\r\n", "\n")
